name: MegaLinter

on:
  workflow_dispatch:
  push:

permissions: read-all

jobs:
  build:
    name: MegaLinter
    runs-on: ubuntu-latest
    permissions:
      contents: write
      statuses: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: MegaLinter
        uses: megalinter/megalinter@v7.1.0
        env:
          BASH_SHFMT_ARGUMENTS: --indent 2 --space-redirects
          DISABLE_LINTERS: SPELL_CSPELL
          FORMATTERS_DISABLE_ERRORS: false
          GITHUB_COMMENT_REPORTER: false
          GITHUB_STATUS_REPORTER: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MARKDOWN_MARKDOWNLINT_CONFIG_FILE: LINTER_DEFAULT
          PRINT_ALPACA: false
          REPOSITORY_KICS_ARGUMENTS: --exclude-paths .github/workflows/renovate.yml
          VALIDATE_ALL_CODEBASE: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch' }}
